config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'scoresheets' => 'scoresheets#index'
  post 'scoresheets' => 'scoresheets#index'
  post 'scoresheets/:id' => 'scoresheets#edit'
  get 'scoresheets/:id' => 'scoresheets#edit'
  patch 'scoresheets/:id' => 'scoresheets#update'
  root 'static_pages#home'
  get '/static_pages/admin', to: 'static_pages#admin'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :scoresheets,          only: [:index, :create, :destroy, :edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By: Bahareh Mokarram Dorri
  </small>
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <% if current_user.admin? %>
        <li><%= link_to "Home", 'static_pages/admin' %></li>
        <% else %>
               <li><%= link_to "Home", root_path %></li>
        <% end %>
        <% end %>
        <% if logged_in? %>
        <% if current_user.admin? %>
        |           <li><%= link_to "Users", users_path %></li>
                    <li><%= link_to "Teams", scoresheets_path %></li>
        <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
              <% else %>
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% end %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
     
    </div>
  </body>